### ISSUE TITLE
Add logging of gas so we have an idea what it is

### ISSUE THREAD

**Issue by shanev** [TruStory/truchain#466]

**Comment by mohitmamoria** [comment]
[ ![Mailman Logo](https://mailcoach.mailmanhq.com/storage/2/conversions/Logo-horizontal---Duo-Royal-blue-&-Steel-gray-image.png "Mailman Logo") ](https://www.mailmanhq.com?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+1)        

 

 

   

 

 

                      

 

 

   

 

 

       Hey!

  
This is Mohit, CEO of [Mailman](https://mailman.to/cold-drip-1?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+1). You might have taken one of my email courses or read [my book on productivity](https://www.mailmanhq.com/tiny-book?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+1).

  
But do you know the story of how Mailman got started?

Grab some 🍿 popcorn!

\--

  
The year was 2017, I started one of the world's first crypto fund. We were doing really well. Owing to that I used to receive a lot of emails from investors, prospects, and many cold emails.

  
In 2020, I completed the fund's cycle and commitment. I handed the reins to my partner for the second cycle and I exited the fund. It was still doing great, but at that point, I realized that I wasn’t really a money guy. I am a maker.

Even though I exited the fund, the emails still kept coming in. And they even started coming in my personal inbox. Every day, I was spending 80% of my time doing emails.

I was taking some time off to figure out what I should build next, but my inbox became a massive distraction. So I built a very small script for Gmail that did just one thing: hold back all the emails so they would only enter my inbox every four hours.

Every 4 hours, I would get a fresh batch of emails, but in between these batches, I was completely free and undistracted. I spent those four hours exploring ideas that I could build next.

In February of 2020, a friend of mine shared [a tweet from Andrew Wilkinson](https://twitter.com/awilkinson/status/1229451446082555904?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+1) with me, where he asked how to receive batches of email a few times a day, instead of having email just flowing in constantly. My friend knew about the Gmail script I was using, which solved exactly the problem Andrew mentioned in the tweet.

I immediately sent an email to Andrew with the steps to achieve it in Gmail. The reply he sent to me was: “Do you think this can be a business?”

💥 Boom, that struck me!

Everything fell into place. Funnily enough, the script I was using to look for my next business idea, turned out to have an amazing business potential in itself.

That is what we call [Mailman](https://mailman.to/colddrip-1?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+1) today. It is a much-refined version of what we started with and helps 1000s of professionals around the world take control of their overflowing inboxes.

Every time I share this story, it feels surreal. From a tweet to a company, whoa!

***Have you tried Mailman yet? Not yet? You’re missing out!***

Sign up via [this link](https://mailman.to/colddrip-1?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+1) and I'll add 30% discount on your annual subscription (when you choose to upgrade).

👋 Talk soon.

**Mohit Mamoria**

CEO, Mailman

 

     

 

 

   

 

 

                      

 

 

   

 

 

       *To stop receiving these emails from us, [opt-out here](https://mailcoach.mailmanhq.com/unsubscribe/1a61db88-c82b-4bda-bff4-28dbd8dd6678/bde34570-f665-4e39-bcc9-889b9cdb40e8).*

**Comment by mohitmamoria** [comment]
[ ![Mailman Logo](https://mailcoach.mailmanhq.com/storage/2/conversions/Logo-horizontal---Duo-Royal-blue-&-Steel-gray-image.png "Mailman Logo") ](https://www.mailmanhq.com?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+2)        

 

 

   

 

 

                      

 

 

   

 

 

       Hey there!

Have you ever wondered how Elon Musk manages his email inbox?

He must be getting 1000s of emails everyday, right?

The answer is, he doesn’t. His assistant does.

If he managed his inbox, we won’t get to Mars EVERRR!! 😢

But hiring an assistant can be expensive.

Not for ELON MUSK, duh!

Of course not for him, but for the 1000s of other professionals who deal with a flurry of emails every day, mostly by themselves.

They too deserve an assistant, else they’ll spend their entire day in their inbox.

We got something for you!

🎉 [Mailman](https://mailman.to/colddrip-2?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+2), the $10 assistant for your inbox.

We’re not kidding. This thing is real.

Mailman will ensure:

1. You only get emails that you want
2. You only get emails at the time of your choosing
3. Doesn’t let emails disturb you all day long
4. Doesn’t let spam emails inside your inbox
5. Show you time-sensitive emails immediately
 
It can do a lot more. Why don’t you try the services of this $10 assistant for free for 14 days, and then decide if you really want to hire Mailman as your email assistant?

Give it a shot!

If you sign up via [this link](https://mailman.to/colddrip-2?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+2), I'll add 30% discount on your annual plan (when you choose to upgrade!)

👋 Talk soon.

**Mohit Mamoria**

CEO, Mailman

 

     

 

 

   

 

 

                      

 

 

   

 

 

       *To stop receiving these emails from us, [opt-out here](https://mailcoach.mailmanhq.com/unsubscribe/1a61db88-c82b-4bda-bff4-28dbd8dd6678/25f0684f-d3d4-4b95-9195-e6a008489423).*

**Comment by mohitmamoria** [comment]
[ ![Mailman Logo](https://mailcoach.mailmanhq.com/storage/2/conversions/Logo-horizontal---Duo-Royal-blue-&-Steel-gray-image.png "Mailman Logo") ](https://www.mailmanhq.com?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+5)        

 

 

   

 

 

                      

 

 

   

 

 

       Hey there!

Are you a victim of ***unwanted emails*** landing in your inbox out of nowhere?

Here are some eye-opening stats about spam emails:

- Nearly 85% of all emails are spam.
- Scams and fraud comprise only 2.5% of all spam email; however, phishing statistics indicate that identity theft makes up 73% of this figure.
- As many as 85% of all organizations have been targeted by phishing scams in 2021.
- Advertising makes up 36% of all world spam content.
- Fake invoice incidents more than doubled in the first part of 2020.
- Spam emails can be dangerous and can cost you a lot of money and time.
 
This is a long-standing problem.

Not any more!

  
With [Mailman's](https://mailman.to/colddrip-5?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+5) "Block Unimportants" feature puts an end to the spam problem.

  
**How it works?**

Mailman blocks any emails from senders you haven't emailed with before, plus annoying newsletters, notifications, and other distractions. Once a day, we'll send you a digest that shows all the emails Mailman blocked.

With this powerful email management feature, you can choose how you want each sender treated in the future, whether to let it through immediately or automatically block.

Protect your inbox. Protect your time. Do better things!

\--

If you sign up via [this link](https://mailman.to/colddrip-5?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+5), I'll 🎁 add 30% discount to your annual subscription whenever you'll choose to upgrade.

👋 Talk soon.

**Mohit Mamoria**

CEO, Mailman

 

     

 

 

   

 

 

                      

 

 

   

 

 

       *To stop receiving these emails from us, [opt-out here](https://mailcoach.mailmanhq.com/unsubscribe/1a61db88-c82b-4bda-bff4-28dbd8dd6678/22cf6d0e-5565-4ee7-80cf-4657b793b616).*

**Comment by mohitmamoria** [comment]
[ ![Mailman Logo](https://mailcoach.mailmanhq.com/storage/2/conversions/Logo-horizontal---Duo-Royal-blue-&-Steel-gray-image.png "Mailman Logo") ](https://www.mailmanhq.com?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+6)        

 

 

   

 

 

                      

 

 

   

 

 

       Hey there!

Technology was supposed to be a tool for humans. But as of today, we have become a tool of technology.

That means, our technology has more control over us, than the control we exercise over technology.

With your inbox, it’s no different.

Emails keep coming in all day long, whenever they want.

Doesn’t matter if we’re sleeping, eating, driving, or trying to focus.

\*tingggg\* 📬 the notification goes and we’re distracted from whatever we were doing.

Others can grab our attention by dropping a casual "hey up for a quick call?"

Your attention should not be so cheaply available.

You should control when emails land in your inbox, and then tackle your emails when you’re prepared for them, with a focused state of mind.

But how can you decide when emails land in your inbox?

With [Mailman](https://mailman.to/colddrip-6?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+6), you can! (oooh that rhymed so well!)

Mailman lets you decide when and what emails should land in your inbox.

Giving YOU complete control of your inbox.

\--

If you sign up via [this link](https://mailman.to/colddrip-6?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+6), I'll make sure to add 30% discount to the annual subscription whenever you choose to upgrade.

👋 Talk soon.

Mohit Mamoria

CEO, Mailman

 

     

 

 

   

 

 

                      

 

 

   

 

 

       *To stop receiving these emails from us, [opt-out here](https://mailcoach.mailmanhq.com/unsubscribe/1a61db88-c82b-4bda-bff4-28dbd8dd6678/4e0751a8-0a1b-4697-afb4-0db45cc20291).*

**Comment by mohitmamoria** [comment]
[ ![Mailman Logo](https://mailcoach.mailmanhq.com/storage/2/conversions/Logo-horizontal---Duo-Royal-blue-&-Steel-gray-image.png "Mailman Logo") ](https://www.mailmanhq.com?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+7)        

 

 

   

 

 

                      

 

 

   

 

 

       Hey there!

How many times have you replied to an old important email saying "sorry it got lost in my inbox"?

***Too many times?*** Don’t worry you’re not alone.

Important emails getting lost among unimportant emails is a problem almost every professional faces.

Just because of this seemingly trivial problem, you miss out on opportunities and important emails that needed immediate attention.

How do we fix this weird problem of important emails getting lost?

🎉 [Mailman](https://mailman.to/colddrip-7?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+7) is the solution. With its **VIP List** feature, it ensures you never miss out on important emails.

**How it works?**

Inside Mailman, you can use the "VIP List" feature to create a list of important people whose emails you should receive immediately, without any delay.

This coupled with the "Block Unimportants" feature makes sure your inbox remains clean of random clutter, and you see the important emails loud and clear in your inbox as soon as they arrive.

Sign up now for free at [this link](https://mailman.to/colddrip-7?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+7) and I'll make sure to add 30% discount to your annual subscription whenever you choose to upgrade!

👋 Talk soon.

**Mohit Mamoria**

CEO, Mailman

 

     

 

 

   

 

 

                      

 

 

   

 

 

       *To stop receiving these emails from us, [opt-out here](https://mailcoach.mailmanhq.com/unsubscribe/1a61db88-c82b-4bda-bff4-28dbd8dd6678/51707599-aee5-4142-957d-0e83bbd9388f).*

**Comment by mohitmamoria** [comment]
[ ![Mailman Logo](https://mailcoach.mailmanhq.com/storage/2/conversions/Logo-horizontal---Duo-Royal-blue-&-Steel-gray-image.png "Mailman Logo") ](https://www.mailmanhq.com?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+8)        

 

 

   

 

 

                      

 

 

   

 

 

       Hey there!

Email was a tool built to get work done, but today it has become a distraction from that.

For most professionals, the email notifications popping up in the corner of the screen is a serious distraction. Not only does it prevent them from getting the tasks done, but it also makes it difficult to get back at work, with the same state of mind.

This goes seriously against the concept of **Deep Work**.

Georgetown professor Cal Newport defines "deep work" as "the ability to focus without distraction on a cognitively demanding task."

To make it clear, the email itself isn’t the problem, it’s the constant influx of emails that hamper our ability to practice deep work.

🎉 **The fix:** Get emails at fixed times during the day.

[Mailman](https://mailman.to/colddrip-8?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+8) is a tool, that allows you to receive your emails in batches, at times pre-decided by you. This ensures there are no constant email pop-ups and you can focus on your work for a long stretch of time.

1000s of professionals around the world use Mailman to fight email distractions, and practice deep work every day.

\--

Sign up now for free at [this link](https://mailman.to/colddrip-8?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+8) and start doing more deep work on any given day!

👋 Talk soon.

**Mohit Mamoria**

CEO, Mailman

 

     

 

 

   

 

 

                      

 

 

   

 

 

       *To stop receiving these emails from us, [opt-out here](https://mailcoach.mailmanhq.com/unsubscribe/1a61db88-c82b-4bda-bff4-28dbd8dd6678/606030c5-cb00-42b1-8b3a-e68e656fa4c8).*

**Comment by mohitmamoria** [comment]
[ ![Mailman Logo](https://mailcoach.mailmanhq.com/storage/2/conversions/Logo-horizontal---Duo-Royal-blue-&-Steel-gray-image.png "Mailman Logo") ](https://www.mailmanhq.com?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+9)        

 

 

   

 

 

                      

 

 

   

 

 

       Hey there!

A 2018 survey by Adobe of over 1,000 office workers in the USA found they spent an average of 3.1 hours a day on work email, plus 2.5 hours per weekday on personal email.

That's an average of 5.6 hours of your valuable time each day ***just on email***!

If we take an 8-hour workday, subtract 5.6 hours of time spent on email.

We’re left with, 2.4 hours. Take out 1 hour for lunch.

1.4 hours. Take out 0.4 hours of casual chit-chats/unproductive time.

**1 hour.** That’s the amount of time left for deep work.

It’s an absolute waste of human potential to be spending so much time inside the inbox, and almost no time outside of inbox.

**What’s the fix?**

🎉 Receive your emails in batches, at specific times during the day.

[Mailman](https://mailman.to/colddrip-9?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+9) helps you set this up in just 5 minutes.

This will ensure you’re doing less reactionary work, and have more time to do focused deep work.

Sign up for free at [this link](https://mailman.to/colddrip-9?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+9) and think out of the (in)box!

👋 Talk soon.

**Mohit Mamoria**

CEO, Mailman

 

     

 

 

   

 

 

                      

 

 

   

 

 

       *To stop receiving these emails from us, [opt-out here](https://mailcoach.mailmanhq.com/unsubscribe/1a61db88-c82b-4bda-bff4-28dbd8dd6678/232a6e1f-1d70-46c3-b4c4-36f1e714a5e0).*

**Comment by mohitmamoria** [comment]
[ ![Mailman Logo](https://mailcoach.mailmanhq.com/storage/2/conversions/Logo-horizontal---Duo-Royal-blue-&-Steel-gray-image.png "Mailman Logo") ](https://www.mailmanhq.com?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+10)        

 

 

   

 

 

                      

 

 

   

 

 

       Hey there!

It’s 11 PM, you’re done with your work, and are set to retire to sleep.

Just then you hear the sound of an email notification on your phone. Should you check?

What if it’s your boss? What if it’s urgent? What if you’re being fired?

Calm down, my friend. You have ***email anxiety***.

\--

Email anxiety is a deep-rooted fear of looking through your inbox – coupled with an innate inability not to.

Striking any time day or night, sufferers feel intense anxiety around their inbox – worried about both receiving emails and having to read them.

The only way to fix this is to establish clear and strong boundaries around when you’ll tend to your emails. Have a fixed schedule for your inbox, and only open your inbox during those times.

I know what you’re thinking, ***it’s not as easy as it sounds***.

It requires a world of power to NOT click on that email notification.

But ***what if that email only arrives in your inbox when you want it to***?

Oh yes, you need to practice email batching. A practice of only receiving emails in batches, at select times during the day.

🎉 [Mailman](https://mailman.to/colddrip-10?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+10) is a simple tool that allows you to choose your email delivery slots, and only receive emails when you’re mentally prepared to attend them.

It is no less than a blessing if you suffer from email anxiety.

Sign up for free at [this link](https://mailman.to/colddrip-10?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+10) and beat the email anxiety out of the park!

👋 Talk soon.

**Mohit Mamoria**

CEO, Mailman

 

     

 

 

   

 

 

                      

 

 

   

 

 

       *To stop receiving these emails from us, [opt-out here](https://mailcoach.mailmanhq.com/unsubscribe/1a61db88-c82b-4bda-bff4-28dbd8dd6678/0c33ada9-a4aa-41ea-8a5e-7d534968c459).*

**Comment by mohitmamoria** [comment]
[ ![Mailman Logo](https://mailcoach.mailmanhq.com/storage/2/conversions/Logo-horizontal---Duo-Royal-blue-&-Steel-gray-image.png "Mailman Logo") ](https://www.mailmanhq.com?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+3)        

 

 

   

 

 

                      

 

 

   

 

 

       Hey there!

Did you know, an average professional receives and send about [121 emails everyday](https://www.theguardian.com/technology/shortcuts/2019/apr/08/how-many-work-emails-is-too-many?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+3) (via The Guardian)?

Let’s take a conservative estimate of 80 emails/day to do some math.

If you make $80,000 a year and get 80 emails every day.

Then, as per the inbox calculator on our [website](https://mailman.to/colddrip-3?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+3), you are wasting 32 hours and $1297 in your inbox every year.

What if I told you, you can save these 32 hours and $1297 at a fraction of the cost?

🚀 Meet [Mailman](https://mailman.to/colddrip-3?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+3), your personal email assistant.

It costs $10/month, and will save you all that time and money from going down the drain of your inbox.

If you sign up via [this link](https://mailman.to/colddrip-3?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+3), I'll make sure to add 30% discount to your annual subscription (when you decide to upgrade).

👋 Talk soon.

**Mohit Mamoria**

CEO, Mailman

 

     

 

 

   

 

 

                      

 

 

   

 

 

       *To stop receiving these emails from us, [opt-out here](https://mailcoach.mailmanhq.com/unsubscribe/1a61db88-c82b-4bda-bff4-28dbd8dd6678/6d1ab2e5-e2cb-454e-845f-09d59b2d7db4).*

**Comment by mohitmamoria** [comment]
[ ![Mailman Logo](https://mailcoach.mailmanhq.com/storage/2/conversions/Logo-horizontal---Duo-Royal-blue-&-Steel-gray-image.png "Mailman Logo") ](https://www.mailmanhq.com?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+4)        

 

 

   

 

 

                      

 

 

   

 

 

       Hey there!

According to the book – [Unsubscribe](https://jkglei.com/unsubscribe/?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+4) – an average person checks their email 11 times per hour, processes 122 messages a day, and spends 28% of their total workweek managing their inbox. What was once a powerful and essential tool for doing our daily work has become a near-constant source of frustration, anxiety, and distraction from our work.

  
The problem is, emails just keep pouring in ALL THE TIME. That too at the time of others’ choosing. We have no control over our inbox!

  
This should not be like this. You should control when emails land in your inbox, and then, handle them in batches. Instead of the default way of checking your inbox all the time. Batched emails at pre-set times during the day are the way to go.

  
**What is batched emailing?**

"Batched emailing" is not too different from batched meetings. It refers to the technique of processing your incoming emails in batches at pre-specified times, instead of handling them as they come in. So the rest of the day isn’t spent checking your inbox, and can instead be utilized for distraction-free work.

  
**How to practice "batched emailing"?**

1. Close the inbox tab in your browser. Most of us keep it opened all the time, thus, inviting it to distract us.
2. Add two or three slots of twenty minutes each on your calendar for every weekday.
3. Open your inbox only during those slots, and process the pending emails.
 
**How to practice "batched emailing" with Mailman?**

1. Sign up for Mailman from the [Mailman's website](https://mailman.to/colddrip-4?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+4) (works with all popular email clients).
2. Create a free account using Gmail account on which you want to implement batched emailing.
3. Set your emailing schedule ie. the times at which you want your emails to land in your inbox.
4. Set up VIPs (emails that should reach you immediately without any delay).
 
🎉 You’re set! Now you’ve complete control of your inbox and your attention. Just the way it should be.

\--

If you sign up using [this link](https://mailman.to/colddrip-4?utm_source=newsletter&utm_medium=email&utm_campaign=Cold+4), I'll make sure to add a 30% discount to your annual subscription (when you choose to upgrade your account).

👋 Talk soon.

**Mohit Mamoria**

CEO, Mailman

 

     

 

 

   

 

 

                      

 

 

   

 

 

       *To stop receiving these emails from us, [opt-out here](https://mailcoach.mailmanhq.com/unsubscribe/1a61db88-c82b-4bda-bff4-28dbd8dd6678/e32a7184-292f-470b-a65a-ffc65b662f88).*
